apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2023-05-19T07:14:14Z'
  generation: 3
  labels:
    app.kubernetes.io/instance: ocp-gitp-git
    app.kubernetes.io/name: ocp-gitp-git
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    pipeline.openshift.io/runtime: nodejs
    pipeline.openshift.io/runtime-version: latest
    pipeline.openshift.io/type: kubernetes
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:operator.tekton.dev/operand-name': {}
            'f:pipeline.openshift.io/runtime': {}
            'f:pipeline.openshift.io/runtime-version': {}
            'f:pipeline.openshift.io/type': {}
        'f:spec':
          .: {}
          'f:finally': {}
          'f:params': {}
          'f:resources': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2023-05-19T07:52:33Z'
  name: ocp-gitp-git
  namespace: dev
  resourceVersion: '7917152'
  uid: b16628eb-a21f-483f-a00f-502b9c712d23
spec:
  params:
    - default: ocp-gitp-git
      name: APP_NAME
      type: string
    - default: 'https://github.com/nutanix-japan/ocp-gitp.git'
      name: GIT_REPO
      type: string
    - name: GIT_REVISION
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/dev/ocp-gitp-git'
      name: IMAGE_NAME
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
    - default: latest
      name: VERSION
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-nodejs
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
      params:
        - name: SCRIPT
          value: oc rollout status deploy/$(params.APP_NAME)
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: tag-good-image
      params:
        - name: SCRIPT
          value: >-
            oc tag dev/$(params.APP_NAME):latest
            dev/$(params.APP_NAME):promote-stage
        - name: VERSION
          value: latest
      runAfter:
        - deploy
      taskRef:
        kind: Task
        name: openshift-client
    - name: deploy-to-stage
      params:
        - name: SCRIPT
          value: >-
            oc project stage

            oc delete all --selector app=$(params.APP_NAME)

            oc new-app dev/$(params.APP_NAME):promote-stage -n stage
            --as-deployment-config --port='3000'

            oc scale --replicas=2 dc $(params.APP_NAME)

            oc expose service $(params.APP_NAME) --port='3000'
            --path='/ocp-gitp/'
        - name: VERSION
          value: latest
      runAfter:
        - tag-good-image
      taskRef:
        kind: Task
        name: openshift-client
  workspaces:
    - name: workspace
